export const SINGLE_IDEAS = [
    "Coordinated stops",
    "Something funky",
    "Smooth jazz feel",
    "Adolescent punk",
    "Beautiful and atmospheric",
    "Tension and release",
    "Something syncopated",
    "A love song",
    "12-bar blues",
    "A weird rhythm",
    "Palm-muted guitar",
    "Walking bassline",
    "Something your past self would love",
    "Slow guitar riff",
].sort()

export const CONTRAST_IDEAS = [
    "Syncopation",
    "Sudden stops",
    "Ethereal guitar",
    "Walking bass",
    "Tresillo rhythm",
    "Salsa feel",
    "Chunky guitar riffs",
    "Sparse drums",
    "Sparse guitar licks",
    "Spacious bass",
    "Ripping guitar solos",
    "Oud energy",
    "Exciting, dense drums",
    "Beautiful tap guitar",
    "Shimmering summer vibes",
    "Big delays",
    "A grindy bass riff",
    "Many small drum solos",
    "Adolescent lyrics",
    "Pretty background vocals",
    "50s rock ballad feel",
    "Hair metal energy",
    "Sci-fi lyrics",
    "Anti-capitalist lyrics",
    "70s rock vibes",
    "Top 40 vibes",
    "Slow strum pattern",
    "Slow finger picking",
].sort()
