export const SINGLE_IDEAS = [
    "Coordinated stops",
    "Something funky",
    "Smooth jazz feel",
    "Adolescent punk",
    "Beautiful and atmospheric",
    "Tension and release",
    "Something syncopated",
    "A love song",
    "12-bar blues",
    "A weird rhythm",
    "Palm-muted guitar",
    "Walking bassline",
    "Something your past self would love",
].sort()
